improve error reporting, log to stderr

diff --git a/cmd/build b/cmd/build
--- a/cmd/build
+++ b/cmd/build
@@ -32,7 +32,7 @@ EOF
 fi
 if [ ! -e $BUILD_PKG/build.sh ]
 then
-  echo "unrecognized pkg $pkg, missing build.sh"
+  >&2 echo "unrecognized pkg $pkg, missing build.sh"
   exit 1
 fi
 
@@ -114,9 +114,9 @@ EOF
   # run build script
   logfile=$BUILD_OUT/build.log
   fail() {
-    cat $logfile
-    echo ""
-    echo "error building pkg $pkg $pkgid"
+    >&2 cat $logfile
+    >&2 echo ""
+    >&2 echo "error building pkg $pkg $pkgid"
     exit 1
   }
 
diff --git a/tools/need b/tools/need
--- a/tools/need
+++ b/tools/need
@@ -7,8 +7,8 @@ name=${2:-$pkg}
 dst=$BUILD_DEPS/$name
 if [ -d $dst ]
 then
-  echo "error in need: destination already exists. consider passing a name."
-  echo "dst=$dst"
+  >&2 echo "error in need: destination already exists. consider passing a name."
+  >&2 echo "dst=$dst"
   exit 1
 fi
 
diff --git a/tools/untar b/tools/untar
--- a/tools/untar
+++ b/tools/untar
@@ -1,10 +1,15 @@
 #!/usr/bin/env sh
 set -e
 
-src=$1
+src=$(realpath $1)
 dst=$2
 strip=${3:-1}
 
 rm -rf $dst
 mkdir -p $dst
+
+if [ -z "$src" ]
+then
+  >&2 echo "missing src for tar, dst=$dst"
+fi
 tar xf $src -C $dst --strip-components=$strip
