Add host os and isa, log failures

diff --git a/cmd/build b/cmd/build
--- a/cmd/build
+++ b/cmd/build
@@ -12,6 +12,8 @@ EXTRA_ARGS="$@"
 BUILD_ROOT=${BUILD_ROOT:-$PWD}
 BUILD_CACHE=$BUILD_ROOT/build/cache
 ARCH_HOST=$(zig targets | grep "\"triple\"" | cut -d '"' -f4)
+ARCH_HOST_ISA=$(echo $ARCH_HOST | cut -d '-' -f1)
+ARCH_HOST_OS=$(echo $ARCH_HOST | cut -d '-' -f2 | cut -d '.' -f1)
 ARCH=${ARCH:-$ARCH_HOST}
 ARCH_ISA=$(echo $ARCH | cut -d '-' -f1)
 ARCH_OS=$(echo $ARCH | cut -d '-' -f2 | cut -d '.' -f1)
@@ -93,6 +95,14 @@ then
   mkdir -p $BUILD_CACHE/logs
   logfile=$BUILD_CACHE/logs/$pkgid.log
 
+  fail() {
+    cat $logfile
+    echo ""
+    echo "error building pkg $pkg $pkgid"
+    echo "logfile (output above): $logfile"
+    exit 1
+  }
+
   rm -rf $build_out
   mkdir -p $build_out
   env -i \
@@ -110,7 +120,7 @@ then
     BUILD_DEPS=$BUILD_DEPS \
     BUILD_PKG=$pkgdir \
   /bin/sh $pkgdir/build.sh $EXTRA_ARGS \
-    > $logfile
+    > $logfile || fail
   touch $build_out/.ok
 fi
 echo $pkgid
